#!/bin/bash

pyuic6 "ui/activity_monitor_screen.ui" -o "ui_py/activity_monitor_ui.py"
pyuic6 "ui/activity_summary_screen.ui" -o "ui_py/activity_summary_ui.py"
pyuic6 "ui/confirm_food_screen.ui" -o "ui_py/confirm_food_ui.py"
pyuic6 "ui/create_food_plan_screen.ui" -o "ui_py/create_food_plan_ui.py"
pyuic6 "ui/daily_challenge_screen.ui" -o "ui_py/daily_challenge_ui.py"
pyuic6 "ui/find_route_screen.ui" -o "ui_py/find_route_ui.py"
pyuic6 "ui/food_info_screen.ui" -o "ui_py/food_info_ui.py"
pyuic6 "ui/food_plan_summary_screen.ui" -o "ui_py/food_plan_summary_ui.py"
pyuic6 "ui/grocery_planner_screen.ui" -o "ui_py/grocery_planner_ui.py"
pyuic6 "ui/main_menu_screen.ui" -o "ui_py/main_menu_ui.py"
pyuic6 "ui/my_vouchers_screen.ui" -o "ui_py/my_vouchers_ui.py"
pyuic6 "ui/notification_screen.ui" -o "ui_py/notification_ui.py"
pyuic6 "ui/redeem_points_screen.ui" -o "ui_py/redeem_points_ui.py"
pyuic6 "ui/register_meal_screen.ui" -o "ui_py/register_meal_ui.py"
pyuic6 "ui/route_result_screen.ui" -o "ui_py/route_result_ui.py"
pyuic6 "ui/scan_qr_screen.ui" -o "ui_py/scan_qr_ui.py"
pyuic6 "ui/select_activity_screen.ui" -o "ui_py/select_activity_ui.py"
pyuic6 "ui/select_route_screen.ui" -o "ui_py/select_route_ui.py"
pyuic6 "ui/weekly_progress_screen.ui" -o "ui_py/weekly_progress_ui.py"
