[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "pyqt6>=6.9.0",
    "pyside6>=6.9.0",
    "tomlkit>=0.13.2",
]
