# Form implementation generated from reading ui file 'ui/confirm_food_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 917)
        Form.setStyleSheet("background-color: #f4f4f4; border: 1px solid #000000;")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 321, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: gray; border: none;")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton_9 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 320, 181, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 390, 181, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(170, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black;\n"
"border: 0;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;\n"
"border: 0;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(150, 270, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: black;\n"
"border: 0;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CONFIRM FOOD"))
        self.pushButton_9.setText(_translate("Form", "Yes"))
        self.pushButton_10.setText(_translate("Form", "No"))
        self.label_2.setText(_translate("Form", "Detected:"))
        self.label_3.setText(_translate("Form", "Chicken"))
        self.label_4.setText(_translate("Form", "Is this correct?"))
