# Form implementation generated from reading ui file 'ui/redeem_points_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 917)
        Form.setStyleSheet("background-color: #f4f4f4; border: 1px solid ")
        self.pushButton_11 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border: 0;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(80, 80, 281, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: gray; border: none;")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 180, 190, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_3.setGeometry(QtCore.QRect(310, 330, 79, 26))
        self.comboBox_3.setStyleSheet("color: f4f4f4;  \n"
"background-color: #f4f4f4;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 410, 79, 26))
        self.comboBox_4.setStyleSheet("color: f4f4f4;  \n"
"background-color: #f4f4f4;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_5.setGeometry(QtCore.QRect(310, 490, 79, 26))
        self.comboBox_5.setStyleSheet("color: f4f4f4;  \n"
"background-color: #f4f4f4;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_12 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 630, 381, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(20, 390, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(20, 470, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(20, 540, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_11.setObjectName("label_11")
        self.comboBox_6 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_6.setGeometry(QtCore.QRect(310, 560, 79, 26))
        self.comboBox_6.setStyleSheet("color: f4f4f4;  \n"
"background-color: #f4f4f4;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(270, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_11.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "REDEEM POINTS"))
        self.pushButton_5.setText(_translate("Form", "My Vouchers"))
        self.comboBox_3.setItemText(0, _translate("Form", "0"))
        self.comboBox_3.setItemText(1, _translate("Form", "1"))
        self.comboBox_3.setItemText(2, _translate("Form", "2"))
        self.comboBox_3.setItemText(3, _translate("Form", "3"))
        self.comboBox_3.setItemText(4, _translate("Form", "4"))
        self.comboBox_3.setItemText(5, _translate("Form", "5"))
        self.comboBox_3.setItemText(6, _translate("Form", "6"))
        self.comboBox_3.setItemText(7, _translate("Form", "7"))
        self.comboBox_4.setItemText(0, _translate("Form", "0"))
        self.comboBox_4.setItemText(1, _translate("Form", "1"))
        self.comboBox_4.setItemText(2, _translate("Form", "2"))
        self.comboBox_4.setItemText(3, _translate("Form", "3"))
        self.comboBox_4.setItemText(4, _translate("Form", "4"))
        self.comboBox_4.setItemText(5, _translate("Form", "5"))
        self.comboBox_4.setItemText(6, _translate("Form", "6"))
        self.comboBox_4.setItemText(7, _translate("Form", "7"))
        self.comboBox_5.setItemText(0, _translate("Form", "0"))
        self.comboBox_5.setItemText(1, _translate("Form", "1"))
        self.comboBox_5.setItemText(2, _translate("Form", "2"))
        self.comboBox_5.setItemText(3, _translate("Form", "3"))
        self.comboBox_5.setItemText(4, _translate("Form", "4"))
        self.comboBox_5.setItemText(5, _translate("Form", "5"))
        self.comboBox_5.setItemText(6, _translate("Form", "6"))
        self.comboBox_5.setItemText(7, _translate("Form", "7"))
        self.pushButton_12.setText(_translate("Form", "Redeem"))
        self.label_8.setText(_translate("Form", "Masoutis, 1500pt -> 4$"))
        self.label_9.setText(_translate("Form", "AB, 1500pt -> 4$"))
        self.label_10.setText(_translate("Form", "Sklavenitis, 1500pt -> 4$"))
        self.label_11.setText(_translate("Form", "Galaxias, 1500pt -> 4$"))
        self.comboBox_6.setItemText(0, _translate("Form", "0"))
        self.comboBox_6.setItemText(1, _translate("Form", "1"))
        self.comboBox_6.setItemText(2, _translate("Form", "2"))
        self.comboBox_6.setItemText(3, _translate("Form", "3"))
        self.comboBox_6.setItemText(4, _translate("Form", "4"))
        self.comboBox_6.setItemText(5, _translate("Form", "5"))
        self.comboBox_6.setItemText(6, _translate("Form", "6"))
        self.comboBox_6.setItemText(7, _translate("Form", "7"))
        self.label_12.setText(_translate("Form", "My Points:\n"
"2300"))
