# Form implementation generated from reading ui file 'ui/register_meal_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 917)
        Form.setStyleSheet("background-color: #f4f4f4; border: 1px solid ")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 500, 331, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_11 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 60, 41, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border: 0;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 50, 311, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: gray; border: none;")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(50, 600, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 370, 59))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    color: black;  \n"
"background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #888888; \n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(parent=Form)
        self.radioButton.setGeometry(QtCore.QRect(30, 240, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 300, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 360, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 420, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color: ffffff;background-color: #00000000;\n"
"border-radius: 6px;\n"
"    padding: 5px;")
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_5.setText(_translate("Form", "Add selected item to calorie intake"))
        self.pushButton_11.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "REGISTER MEAL"))
        self.label_4.setText(_translate("Form", "Calories consumed today: \n"
"500"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Search for Food:(INOP)"))
        self.radioButton.setText(_translate("Form", "X(X kcal)"))
        self.radioButton_2.setText(_translate("Form", "X(X kcal)"))
        self.radioButton_3.setText(_translate("Form", "X(X kcal)"))
        self.radioButton_4.setText(_translate("Form", "X(X kcal)"))
